apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mugilan1702/multi-backend:v1
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "development"      # dev env variable
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001                   # dev backend port