FROM python:3.12-alpine
WORKDIR /app
RUN apk update && apk upgrade --no-cache && \
    rm -rf /var/cache/apk/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
RUN adduser -D appuser
USER appuser
EXPOSE 5000
CMD ["python", "app.py"]